In [3]:
import torch
print(torch.__version__)

1.7.0+cpu


In [4]:
torch.get_default_dtype()

torch.float32

In [5]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [8]:
torch.numel(tensor_arr)

6

In [9]:
# This tensor is an unitialized one. We only define the shape; values randomly
tensor_uninit = torch.Tensor(2,2)
tensor_uninit

tensor([[6.7502e-07, 5.3179e+22],
        [1.6537e-04, 1.0141e-11]])

In [10]:
# This tensor will actually be initialized with some random values.
tensor_init = torch.rand(2,2)
tensor_init

tensor([[0.8224, 0.6285],
        [0.8732, 0.3483]])

In [11]:
# We can override the default tensors type
# If you're creating Tensors on a GPU the tensor types will be specified using different classes
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

In [12]:
 tensor_fill = torch.full((2,6), fill_value=10)
 tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [14]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_zeroes = torch.zeros_like(tensor_of_ones)
print(tensor_of_ones)
print(tensor_of_zeroes)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [15]:
i = torch.tensor([[0,1,1],[2,2,0]])
v = torch.tensor([3,4,5], dtype=torch.float32)
# A sparse tensor in coordinate format with non-zero elements at indices with the given values
sparse_tensor = torch.sparse_coo_tensor(i, v, [2,5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

In [19]:
init_tensor = torch.rand(2,3)
init_tensor

tensor([[0.9169, 0.5565, 0.2499],
        [0.2461, 0.4867, 0.1228]])

In [20]:
init_tensor.fill_(10)
init_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [21]:
# In-place vs out-place operations
new_tensor = init_tensor.add(5)
init_tensor.add_(11)
print(new_tensor)
print(init_tensor)

tensor([[15., 15., 15.],
        [15., 15., 15.]])
tensor([[21., 21., 21.],
        [21., 21., 21.]])


In [22]:
x = torch.linspace(start=0.5, end=10.0, steps=10)
x

tensor([ 0.5000,  1.5556,  2.6111,  3.6667,  4.7222,  5.7778,  6.8333,  7.8889,
         8.9444, 10.0000])

In [23]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.5000, 1.5556, 2.6111, 3.6667]),
 tensor([4.7222, 5.7778, 6.8333, 7.8889]),
 tensor([ 8.9444, 10.0000]))

In [24]:
tensor3 = torch.tensor([3.0,4.0,5.0])
torch.cat((tensor_chunk[0], tensor_chunk[1], tensor3), 0)

tensor([0.5000, 1.5556, 2.6111, 3.6667, 4.7222, 5.7778, 6.8333, 7.8889, 3.0000,
        4.0000, 5.0000])

In [25]:
random_tensor = torch.tensor([[1,2,5], [10,50,20], [2,3,4]])
tensor_view = random_tensor.view(9)
# Changing a value in the original tensor results in the change of the viewed tensor as well
random_tensor[2,0] = 0

print(random_tensor)
print(tensor_view)

tensor([[ 1,  2,  5],
        [10, 50, 20],
        [ 0,  3,  4]])
tensor([ 1,  2,  5, 10, 50, 20,  0,  3,  4])


In [27]:
tensor_clamp = torch.clamp(random_tensor, min=3, max=9)
tensor_clamp

tensor([[3, 3, 5],
        [9, 9, 9],
        [3, 3, 4]])